

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -I/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5
INCPATH       = -I../testApp -I. -isystem \
-I/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/glib-2.0/usr/lib64/glib-2.0/include \
-I/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/glib-2.0/usr/include/glib-2.0 \
-I/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/glib-2.0/usr/include \
-I/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include \
-I/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/ \
-I. -I/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/linux-g++
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testApp1.0.0
LFLAGS        = -Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/imx-gpu-viv/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/libpng/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/harfbuzz/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/icu/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/orc/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/libpcre/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/glib-2.0/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/freetype/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/libffi/usr/lib64/ \
-Wl,-rpath-link,/home/tokai-soft/work/build/tmp/sysroots-components/aarch64/zlib/lib64/
LIBS          = $(SUBLIBS)
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../../

####### Files

SOURCES       = ../testApp/main.cpp 
OBJECTS       = main.o
DIST          = /home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/unix.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/linux.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/qconfig.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		../testApp/.qmake.stash \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/qt.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/resources.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/moc.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/lex.prf \
		../testApp/main.cpp
QMAKE_TARGET  = testApp
DESTDIR       = 
TARGET        = testApp


first: all
####### Build rules

testApp:  $(OBJECTS)  
	$(CXX) $(LFLAGS) -o $(OBJECTS_DIR)$(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: Makefile testApp



clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: ../testApp/main.cpp /home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QtPlugin \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qplugin.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qobject.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qobjectdefs.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qnamespace.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qglobal.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qconfig.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qsystemdetection.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qprocessordetection.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qcompilerdetection.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qtypeinfo.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qsysinfo.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qlogging.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qflags.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qatomic.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qbasicatomic.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qgenericatomic.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qatomic_msvc.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qglobalstatic.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qmutex.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qnumeric.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qversiontagging.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qstring.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qchar.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qbytearray.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qrefcount.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qarraydata.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qstringbuilder.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qlist.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qalgorithms.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qiterator.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qhashfunctions.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qpair.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qbytearraylist.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qstringlist.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qregexp.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qstringmatcher.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qcoreevent.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qscopedpointer.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qmetatype.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qvarlengtharray.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qcontainerfwd.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qobject_impl.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qpointer.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qsharedpointer.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qshareddata.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qhash.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qjsonobject.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qjsonvalue.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QPluginLoader \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qpluginloader.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qlibrary.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QDir \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qdir.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qfileinfo.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qfile.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qfiledevice.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qiodevice.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QTimer \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qtimer.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qbasictimer.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QDebug \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qdebug.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qmap.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qtextstream.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qlocale.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qvariant.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qvector.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qpoint.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qset.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qcontiguouscache.h \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/QThread \
		/home/tokai-soft/work/build/tmp/work/aarch64-poky-linux/qtbase/5.6.3+gitAUTOINC+e6f8b072d2-r0/sysroot-destdir/usr/include/qt5/QtCore/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../testApp/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

